### ISSUE TITLE
Consider dropping near-copycat Django tasks from poetry

### ISSUE THREAD

**Issue by jchristgit** [discord-python/site#672]
We have these tasks in `pyproject.toml` which more or less just delegate to `maange.py` commands:

```toml
[tool.taskipy.tasks]
start = "python manage.py run --debug"
makemigrations = "python manage.py makemigrations"
django_shell = "python manage.py shell"
```

In my opinion, this abstraction is problematic, as most people who used Django know what `manage.py` is and how it works, and recommending usage of wrappers like this creates a feeling that we're using some special functionality here.

This is mentioned, for example, here: https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/site/#webserver

I vote towards removing this and simply mentioning that we are a regular Django project and "these example commands" can be used. For example:

```sh
# Run the development server
python manage.py runserver

# Run tests
python manage.py test

# Create a new migration
python manage.py makemigrations
```
